### ISSUE TITLE
Add Gitlab Release tagging and badge to Gitlab Java template

### ISSUE THREAD

**Issue by eventuri** [chesapeaketechnology/gitlab-templates#66]

**Comment by eventuri** [comment]
Can likely do something like the below.

```
gitlab_release_traceability_job:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "running release_job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
```
